name: PR Checks

on:
  pull_request: 
    branches: 
      - main  
      - master
      
permissions:
  contents: read
  pull-requests: write
  checks: write
  issues: write


jobs:
  test_before_merge:
    runs-on: ubuntu-latest

    strategy:
      fail-fast:  true
      matrix:
        language: ['python']

    steps:
  
      - name: Process Started
        run: echo "Testing Process Started"
    
      - name: Checkout our branch
        uses: actions/checkout@v4

      - name: Checkout Python
        uses: actions/setup-python@v5
        with:
           python-version: "3.11"

      - name: Install dependecies
        run: | 
          pip install flask 

      # - name: Testing Phase
      #   run: |
      #     pip install flake8
      #     # flake8 .  --format=github

      - name: Ready 
        uses: github/codeql-action/init@v4
        with:
          languages: ${{matrix.language}}

      - uses: github/codeql-action/start-proxy@v4
      - uses: github/codeql-action/analyze@v4

      # - name: using ReviewDog
      #   uses: reviewdog/action-flake8@v3
      #   with:
      #     github_token: ${{secrets.GITHUB_TOKEN}}
      #     reporter: github-pr-review
      #     fail_on_error: true

   
        
        
        
        

          

  
    
